### ISSUE TITLE
incomplete themes

### ISSUE THREAD

**Issue by PierreMonico** [docstrap/docstrap#100]
Hi,
First of all, thanks for the great work done in the docstrap project. I have done following things :

1. Using npm : 
  1.1. Installed jsdoc in *myProject/lib/node_modules*
  1.2. Installed docstrap in *myProject/lib/node_modules*

2. Edited the conf.json file in *myProject/lib/node_modules/jsdoc* to : 
  1.1. use the docstrap template : 
  ```
"opts": {
    	"template": "../ink-docstrap/template"
}
  ```

  1.2. copy the ```"templates"``` key  from jsdoc.conf.json contained in *myProject/lib/nodeModules/ink-docstrap* to it. I don't know if this part is right, but I couldn't find another way to do it even after several researches
  1.3. configure the input and output files. 

3. Run following command line : 
```
$ cd myProject/lib/node_modules/.bin
$ jsdoc -c ../jsdoc/conf.json
```
The files are created in the directory I specified in the conf.json as expected. 

The problem is that none of the themes I set in the conf.json matches the render I can see on your description. Some of them don't work at all (plain html output). For example, Amelia won't work at all. The reason for that is probably that I can't find it in the styles folder. I tried to un- and reinstall docstrap several times. 

A. Why don't the themes render correctly (or why are some of them missing)?
B. Where is the best path to install docstrap and how to link it properly to jsdoc?
C. How is the conf file included in docstrap supposed to be used ? By pasting it in the jsdoc conf, or by accessing it somehow in addition to the jsdoc conf ?

I run Windows 7 x64. Thanks for the answers. Having struggled for hours now, I will contribute to the Wiki if I find a solution.

**Comment by terryweiss** [comment]
Here's some advice that may help: 
1) consider the conf.json file a guide, but no more
2) Pathing at the command line and conf.json are relative to where the executable is run
3) install jsdoc gobally using -g with npm
4) Make sure jsdoc works first, then add the template
5) from the root directory of my current project, the conf.json file has this entry for the template:
```
"template"    : "node_modules/ink-docstrap/template",
```
and jsdoc is run from the root of the project

**Comment by esatterwhite** [comment]
I think there is some missing CSS from the boot swatch libs or the html templates are missing the right classes / structured wrong. 

The drop menus  do not render quite right

**Comment by lukeapage** [comment]
Closing after lack of a response, please come back if there is a concrete issue here that isn't raised in another issue.
