### ISSUE TITLE
Error installing with npm

### ISSUE THREAD

**Issue by GochoMugo** [docstrap/docstrap#103]
I tried installing the package with npm:

```bash
$ npm install ink-docstrap
```

but i kept getting this error: (this is v0.5.2)

```bash
npm ERR! tar.unpack untar error /home/gocho/.npm/ink-docstrap/0.5.2/package.tgz
npm ERR! Linux 3.16.0-41-generic
npm ERR! argv "/home/gocho/.nvm/versions/node/v0.12.4/bin/node" "/home/gocho/.nvm/versions/node/v0.12.4/bin/npm" "i" "ink-docstrap"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path /home/gocho/node_modules/ink-docstrap/themes/paper/module-documents_probe.This%2520is%2520not%2520actually%2520a%2520class,%2520but%2520an%2520artifact%2520of%2520the%2520documentation%2520system.html
npm ERR! code ENAMETOOLONG
npm ERR! errno -36

npm ERR! ENAMETOOLONG, open '/home/gocho/node_modules/ink-docstrap/themes/paper/module-documents_probe.This%2520is%2520not%2520actually%2520a%2520class,%2520but%2520an%2520artifact%2520of%2520the%2520documentation%2520system.html'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gocho/npm-debug.log
```

To solve this I had to install the v0.4.12
```bash
⇒ npm i ink-docstrap@0.4.12
ink-docstrap@0.4.12 node_modules/ink-docstrap
└── moment@2.6.0
```

What caused the installing the latest version to error?

**Comment by digital-abyss** [comment]
I'm having this issue as well, but could not solve it even with the above suggested fix, a project's dependency seems to always go and try to use 0.5.2

**Comment by GochoMugo** [comment]
@digital-abyss I was actually installing grunt-jsdoc when I encountered this bug. I ended up cloning the grunt-jsdoc repo instead of npm-installing it.

**Comment by GochoMugo** [comment]
@digital-abyss since I needed to build my packages remotely, I ended up using an older version of `grunt-jsdoc`:

```bash
⇒ npm i grunt-jsdoc@0.6.4
```

So in `package.json`:

```
  "devDependencies": {
    "grunt-jsdoc": "0.6.4"
  }
```

Explicitly use the old version.

**Comment by GochoMugo** [comment]
See the possible reason behind this error at issue #109

**Comment by perry-mitchell** [comment]
Has there been any progress on this? I'm encountering the same issue, and it seems many others are posting similar issues:

https://github.com/terryweiss/docstrap/issues/103
https://github.com/krampstudio/grunt-jsdoc/issues/116

**Comment by bobholt** [comment]
This is due to the ink-docstrap dependency running docs against this line, which generates the filename causing the ENAMETOOLONG error:

https://github.com/terryweiss/docstrap/blob/master/fixtures/documents/probe.js#L1004

See also:
- https://github.com/krampstudio/grunt-jsdoc/issues/142
- https://github.com/terryweiss/docstrap/issues/109

**Comment by lukeapage** [comment]
should be fixed in this release, please report back if not.
