### ISSUE TITLE
Custom style has a broken header

### ISSUE THREAD

**Issue by hellos3b** [docstrap/docstrap#105]
Steps I've taken:

1) Clone repo into a development folder
2) Run "bower install" and "npm install"
3) Modify ./template/jsdoc.conf.json to     "theme": "flatly"
4) Run "grunt apply" and "grunt less"
5) cp template/static/styles/site.flatly.css ~/path/to/docs/styles/

Result: Header is broken and none of the styling looks right ( see screenshot )

![screen shot 2015-06-24 at 11 00 32 am](https://cloud.githubusercontent.com/assets/4062679/8337499/5ef356be-1a60-11e5-9440-0c22922f72f0.png)

It worked fine yesterday, but this morning I tried it again and now everything is broken. Can't seem to figure out what is wrong

**Comment by lukeapage** [comment]
Flatly looks fine in 0.5.3 - http://docstrap.github.io/docstrap/themes/flatly/

will re-open if you still have this issue.
