### ISSUE TITLE
Double Headers on Pages

### ISSUE THREAD

**Issue by gnstanley** [docstrap/docstrap#106]
Previous issue #87 (currently closed) should perhaps be reopened: the double headers error seems to be back. 

It seems that [this line](https://github.com/terryweiss/docstrap/commit/c6e9d29307657e34805230818343657e38ca9c42#diff-1f2e6dffd9f034b975ed415f0220e336R50) in https://github.com/terryweiss/docstrap/commit/c6e9d29307657e34805230818343657e38ca9c42 is the problem. 

On my machine, I fixed the problem by simply deleting the line (linked above) that was added back in. However, I need others to use `npm install` to download a version of docstrap that does not give double headers. Please fix the above issue and push it to master.

Thank you!

**Comment by CaitlinWeb** [comment]
+1 I have also noticed this issue. Thanks for posting the fix.

**Comment by frncesc** [comment]
+1 too. Thank you for the fix!

**Comment by BlueRaja** [comment]
+1

**Comment by fisch0920** [comment]
+1 this is really annoying

**Comment by fisch0920** [comment]
See #116

**Comment by gregpettit** [comment]
+1

**Comment by obimod** [comment]
+1

**Comment by Stryzhevskyi** [comment]
+1

**Comment by lukeapage** [comment]
Fixed and published as 0.5.3
