### ISSUE TITLE
Source file link and index

### ISSUE THREAD

**Issue by tailiu** [docstrap/docstrap#113]
Can I replace the big 'index' word with some meaningful word in the front page? In addition, Can I customize the style of the front page? Thanks.

**Comment by fisch0920** [comment]
See #116

**Comment by lukeapage** [comment]
"Index" removed in 0,5,3

**Comment by nanandn** [comment]
I am using 1.30 (from gulp-jsdoc3). I still see index and I only see one of my source file in the index. 
Is there a way to remove the index?

Anand
