### ISSUE TITLE
Duplicate errors with CommonJS style code

### ISSUE THREAD

**Issue by daprahamian** [docstrap/docstrap#115]
Hello,

I am using Browserify, and when I write code like this:

```js
'use strict';

/**
 * @class x
 */
module.exports = function() {
};
```

I get something that looks like this:

![image](https://cloud.githubusercontent.com/assets/7957497/9307603/7169e7da-44cd-11e5-8968-a1bba5d568a2.png)

Is there a way to eliminate the duplicate `Class: x` at the top?

**Comment by fisch0920** [comment]
See #116

**Comment by lukeapage** [comment]
duplicate of #106
