### ISSUE TITLE
Nested property documentation overlaps with ToC & QuickSearch

### ISSUE THREAD

**Issue by DeX3** [docstrap/docstrap#118]
When a method has documentation about nested object properties for its parameters (which is quite often the case), e.g.:

    /**
     * ...
     *
     * @param {Object} [options] Additional options. 
     * @param {String} [options.source=Model.prototype.name] Each field's source
     * will be prefixed with this string
     * @param {String} [options.aliasPrefix=Model.prototype.name] Each attribute's
     * alias will be prefixed with this string
     * 
     * ...
     */

The table which contains the nested properties will overlap with the QuickSearch & Table of Contents on smaller browser windows (typically this happens to me at < 1580px), effectively making the documentation very hard to read.

This seems to affect all themes.

![Screenshot](http://i.imgur.com/i9ndIRr.png)

Proposed solution:

Hide the quicksearch & ToC on smaller screensizes, or provide a way to hide it manually.

**Comment by ZiperRom1** [comment]
I had the same problem, just had "hidden-xs hidden-md" class to the toc div on layout.tmpl did the job.
