### ISSUE TITLE
CSS Files Creating Massive Load Lag in Chrome

### ISSUE THREAD

**Issue by BAM5** [docstrap/docstrap#120]
There is [an issue](http://superuser.com/questions/656411/why-does-google-chrome-take-so-long-to-refresh-local-files-anyway-to-improve) where referencing urls without the http protocol identifier causes Chrome to lag massively when loading html files locally.

I noticed that many of the css files have the following line of code
```css
@import url("//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700");
```

When I change this line to
```css
@import url("http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700");
```

The jsdoc pages load instantly, as they should, when viewing locally on Chrome.

**Comment by lukeapage** [comment]
So the problem is only when viewing files on the file system right?
if the site is hosted it should be fine and in fact the protocol-less url is required for https/http hosting.

**Comment by lukeapage** [comment]
this is fixed, they are now https (a bootswatch change, not our change)
