### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by joeflack4** [docstrap/docstrap#122]
I'm stuck on installing this, and I'm wondering if maybe the installation portion of the readme could be more newbie friendly if possible? I'd really like to use the themes!

I've got jsdoc installed globally. I install docstrap as a subdirectory. I then place the conf.json in the main directory of jsdoc. When I utilize jsdoc, it is still using the jsdoc base theme.

I've tried messing around a lot of different ways, but it still doesn't seem to be doing anything. I don't think that I installed it correctly ;(

**Comment by lukeapage** [comment]
Did  you get this sorted? its more of a jsdoc issue.. I'm guessing you did and I can close this, since its 2 months old now?

**Comment by joeflack4** [comment]
Not really resolved, unfortunately. I gave up the next day. Not sure whether its a jdoc or docstrap issue. I think documentation automation is awesome, so I'm sure I'll re-visit in the future.

**Comment by mwittig** [comment]
@joeflack4 Next time, try grunt grunt-jsdoc. I have installed it with the latest v0.5.3 of ink-docstrap and it work like a charme :)

**Comment by joeflack4** [comment]
Thx!
