### ISSUE TITLE
Req: Option to completely remove the <footer>

### ISSUE THREAD

**Issue by thealjey** [docstrap/docstrap#123]
I would like to be able to completely remove the `<footer></footer>` element from the docs.
Or at least `<span class="jsdoc-message"></span>` within it.
In my project the documentation is generated every time the source code is re-compiled and I do not want to see a huge change set in GIT every time, even when nothing's really changed but the timestamp.
I'd be great if Docstrap supported the `includeDate` option, just like the default template in JSDoc3 does.

**Comment by thealjey** [comment]
created a PR #149

**Comment by lukeapage** [comment]
merged
