### ISSUE TITLE
Menu cuts off long lists

### ISSUE THREAD

**Issue by srad** [docstrap/docstrap#144]
The top navigation - which lists the items in each category (namespace, modules, ...) - doesn't scroll if the number of items exceeds the vertical screen size.

We have, for example, a pretty big number of classes, only the first x Elements are shown and drop down menu is just cut off, it should be scrollable or something.

**Comment by lukeapage** [comment]
This happened in 1.0.1. It does need fixing, but if you want the design where the drop downs were limited to 300px with overflow, you can pin to 1.0.0 for now.

**Comment by lukeapage** [comment]
fixed in 1.0.3

**Comment by srad** [comment]
Awesome, thank you!
