### ISSUE TITLE
Behaviour of the highlighted index item

### ISSUE THREAD

**Issue by mwittig** [docstrap/docstrap#145]
@lukeapage First of all I would like thank you for your hard work and for taking the initiative on getting the project back on track.  Much appreciated!

There is one point which I still find a bit strange and this has do with the highlighting of an index item. The index can be used to navigate to an item which then will be displayed at the top of the view area. However, if the select item is at the end of index it will displayed at the bottom of the view area (which is OK) and the highlighted item will change immediately to the item displayed at the top of the page (which may not be fully visible). Would it be possible to inihibit this in the case where the user has selected an item from the index? 

Steps to reproduce:
* Open http://docstrap.github.io/docstrap/themes/cosmo/base_chains.html
* Click on the "open" member in the index
* In my case the highlighted element changes to "close" (this depends on the size view area, of course)

What I have also noticed: If I click on "end" or "open" again then "close" will not be highlighted. I guess this is because the displayed area of the page has not changed.

**Comment by lukeapage** [comment]
ok, I think I understand - I did look into it. I could make it not change the selected item after a click animation finishes.. but then if a user scrolls a little it will reset and go to the higher selection again. So its slightly better. 

I can't think of a perfect solution (putting a large margin on the page bottom even appeals) . can you think of anywhere that solves this problem?

**Comment by lukeapage** [comment]
I guess it should ideally work out if any of the header currently selected are shown and then not change them if they are shown, then only switch to a new header if it wasn't previously shown..

**Comment by mwittig** [comment]
@lukeapage I have tried v1.0.4 and it works great. As you say it has to be compromise as highlighting is also used mark the top-most element display while scolling. Thanks for looking into this so quickly.
