### ISSUE TITLE
Search box?

### ISSUE THREAD

**Issue by saeioul** [docstrap/docstrap#146]
Hello! 

Im trying your template and so far it looks great! Just a problem, search box is not showing up in the generated doc files, I've been looking for some configuration that could have disabled it but found none. I've seen this issue reported before and closed, maybe something wrong on my side?

If there is something I can do to help, im willing to do so.

**Comment by lukeapage** [comment]
is the sidebar appearing? both it and search are added with javascript, so if you view locally in ie, js is disabled and you don't see it. if its not that, check the version of ink-docstrap is upto date. 

if its neither of those things,  can you check devtools to see if a js error occurs?

**Comment by saeioul** [comment]
Wow, thanks for the quick response.

Ok, I think the sidebar is appearing (the blue-outlined box in the right) That gets filled with the target methods and members when i select something from the dropdowns. Javascript is up and running and Im on version 1.0.2.

The devtool's js console is silent, here's an screenshot of the index.

![screen shot 2015-12-14 at 16 31 21](https://cloud.githubusercontent.com/assets/5835061/11794614/e4f7a0ea-a277-11e5-9674-6a3280028450.png)

**Comment by saeioul** [comment]
HEY!

I checked carefully and found that I was referring to an outdated install in my buildfiles.

Of course the search box is there. Thanks.

**Comment by lukeapage** [comment]
yes it looks like no js. is that why you closed?

**Comment by saeioul** [comment]
Thing is I had this set up as an ant task. In the task i was referring to a wrong path for the template files. Now that the ant task is correctly set up, the template works as expected.
