### ISSUE TITLE
orange text hard to read

### ISSUE THREAD

**Issue by gbaumgart** [docstrap/docstrap#178]
Hi,
do you realize that all bootstrap themes are having the same defect: pre elements or elements with orange text color are really hard to read: 

![image](https://cloud.githubusercontent.com/assets/1205100/13373362/cbc2193c-dd66-11e5-93e5-e69463ce1088.png)

("Readable")
![image](https://cloud.githubusercontent.com/assets/1205100/13373367/f9a05404-dd66-11e5-8168-ce186dbb5c2e.png)

I mean a bright orange on white is just a bad idea. I know, its not your fault but I wanted to let you know. I also asked some people around and they confirm: its tedious and awful to read. 

Could we add custom CSS through options to fix that? 
thank you.

**Comment by lukeapage** [comment]
You are right - we should override it using a theme variable

**Comment by gbaumgart** [comment]
yeah, you can close this if you like (fixed on my site). but yeah, any option to include a custom css file (abs/rel) would help a lot.

**Comment by lukeapage** [comment]
No, it would be good to fix.
If you make a PR to add an option for a custom css I'll merge it.

**Comment by lukeapage** [comment]
Fixed - no more orange.

**Comment by lukeapage** [comment]
btw it was docstrap's fault - someone decided to override the default colour with orange.. no idea why!!
