### ISSUE TITLE
Link to a line of code does not work

### ISSUE THREAD

**Issue by alphanull** [docstrap/docstrap#2]
While there are links to the source file and also to certain line numbers, the corresponding anchor tag in the source output seems to be missing. So, for example, the doclink points to path/file.js#line123, but there is no anchor named "#123" in path/file.js.html, so the page loads, but does not "jump" to the desired line of code.

**Comment by lukeapage** [comment]
This now works (though the alignment is off as it doesn't take the navbar into account)
