### ISSUE TITLE
Bump npm version

### ISSUE THREAD

**Issue by n1474335** [docstrap/docstrap#311]
Hi, could you bump the npm patch version so that the fix for #310 gets pulled through please? It's currently breaking my builds.

Thanks

**Comment by nicjansma** [comment]
We're hitting this as well -- need a new version released

**Comment by pmeijer** [comment]
Bumping the jsdoc version to 3.5.5 fixed it for me.

https://github.com/jsdoc3/jsdoc/releases/tag/3.5.5

**Comment by lukeapage** [comment]
I published this.. but although I temporarily took over docstrap support a while back, I no longer use docstrap or can remember much about the project. If someone wants to take ownership, please contact myself/terry weiss
