### ISSUE TITLE
Are you welcoming maintainers?

### ISSUE THREAD

**Issue by Telokis** [docstrap/docstrap#327]
Hey guys!

I just found this repo and I wanted to use docstrap for my own projects.
Sadly, the last commit was six months ago and it's pretty insignificant.
Moreover, there are 66 PR open which is an absolutely huge number (even though a lot of from greenkeeper)

What about letting maintainers give a helping hand?
Even though I can't be helping full time, I'd be glad to take a look at all those PRs and issues in order to clean everything a bit.

/cc @lukeapage @terryweiss

**Comment by lukeapage** [comment]
Would you like to step up and help out? I don’t mind giving people access, I would just wait a little bit to see if terry has objections otherwise give you GitHub access and then after a while if things go well, npm access.

**Comment by lukeapage** [comment]
I no longer use docstrap in my projects so it’s hard to get motivated on it.

**Comment by Telokis** [comment]
Even though I probably won't help forever, I need to use docstrap for some projects so I'd be glad to help however I can. (The first thing being going through all those greenkeeper PRs and update dependencies.

**Comment by terryweiss** [comment]
I would love to have someone give this project some love. Luke thanks for
thinking of me. Telokis, whatever you can help out on will be a huge
benefit to all docstrap users.

**Comment by Telokis** [comment]
I'll do my best!
