### ISSUE TITLE
Source path shown with full path under Windows

### ISSUE THREAD

**Issue by mlocati** [docstrap/docstrap#44]
When generating the docs under Windows, the pages show the full path of the source files:

```
Source:
C:/Users/Me/Projects/MyProject/js/sourcefile.js, line 30
```

This does not happen with standard jsdoc:

```
Source:
sourcefile.js, line 30
```

**Comment by Download** [comment]
Could it be that this bug has resurfaced? I am noticing it in the JSDoc output generated by grunt-jsdoc. I logged an issue there but the author says he is using docstrap version 0.5.2 so the bug shouldn't be there right? Still I'm seeing it...

**Comment by shernshiou** [comment]
I am using linux. Any configuration to hide the full path check this:

http://depoio.github.io/node-telegram-bot/Bot.html

**Comment by Download** [comment]
Yup I'm seeing the same thing. I am now manually doing a search replace (replace two path strings with the empty string)... Maybe I will add some grunt task to do the replace there automatically, but I'm still hoping this will be fixed eventually.

**Comment by Download** [comment]
Can this be reopened? There are multiple people still reporting the problem. The grunt plugin has [an open issue](https://github.com/krampstudio/grunt-jsdoc/issues/135) on this as well, but the author thinks it's happening in this project...

**Comment by gordonwoodhull** [comment]
Currently seeing this on OSX.

![image](https://cloud.githubusercontent.com/assets/1366709/12992929/5ebe1ddc-d0e5-11e5-954a-c89ae0f07cff.png)
