### ISSUE TITLE
ScrollSpy offset error

### ISSUE THREAD

**Issue by lopezoscar** [docstrap/docstrap#61]
![docstrapoutofphase](https://cloud.githubusercontent.com/assets/1145939/3577208/57a58f74-0b9a-11e4-8a6c-191ce3ca5769.png)

When I use the scroll, is offset by cutting the description of the methods or locating the focus incorrectly selected method.

In this example, when I do click in closeTransaction, cut description.

Can you help with this problem?

**Comment by lukeapage** [comment]
This is fixed in 0.5.3 and possibly before.
