### ISSUE TITLE
fred:// Protocol

### ISSUE THREAD

**Issue by simpae** [docstrap/docstrap#66]
In `template/static/styles/site.flatly.css:1` the webfont is requested via the protocol `fred://`
This shows up as an error in Chrome and is simply ignored in Firefox.

The same protocol is also used in `docstrap/template/jsdoc.conf.json:22`. (Is this setting even used? It is not documented.)

**Comment by svallory** [comment]
Default protocol is already `html://`. Someone should close this

**Comment by lukeapage** [comment]
closing, please come back if this shouldn't be closed.
