### ISSUE TITLE
@lang inside markdown.

### ISSUE THREAD

**Issue by tswaters** [docstrap/docstrap#74]
Github flavoured markdown already keeps track of which language is being used -- and jsdoc recognizes this and includes a class on the pre, lang-{language}... e.g.,

```html
<pre class="prettyprint source lang-html"><code>
...etc...
</code></pre>
```
It seems to me the @ lang declaration is redundant here and requires additional text where it shouldn't really be necessary (and can't really be hidden).

The code that controls this is in [layout.tmpl](https://github.com/terryweiss/docstrap/blob/master/template/tmpl/layout.tmpl#L109-L131)... it seems to me this should not include the readme section -- for that, it should parse out the lang class, something like the following:

```javascript
var lang = 'plaintext';
var classes = this.classList.toString();
var re = /.*lang-(.*)\s?.*$/i;

if (re.test(classes)) {
  lang = classes.replace(re, '$1');
}

if (lang.toLowerCase() === 'html') {
  lang = 'xml';
}

$(this)
  .addClass( "sunlight-highlight-" + lang )
  .addClass( "linenums" )
  .html( $(this).find( "code" ).html() );
```

Thoughts?

**Comment by lukeapage** [comment]
This is fixed now
