### ISSUE TITLE
Call for maintainers!

### ISSUE THREAD

**Issue by terryweiss** [docstrap/docstrap#75]
docstrap users: My current workload prevents me from giving this project the attention it (and you) deserves. I am looking for a maintainer to help address some of the open issues and update it to  Bootstrap 3. If you are interested, respond to this thread. 

Thanks in advance!

Terry

**Comment by tswaters** [comment]
I'm not sure if I want to be a maintainer (seems like an awful lot of responsibility)... However, I can update the template to use bootstrap 3.

game plan:  update classes in the templates, variable names in the mixins and the references to bootswatch to use their 3.0 versions (this assumes all the templates have 3.0 equivalents)

**Comment by TimOgilvy** [comment]
Would be awesome if build mode was actually runnable.  Getting lots of moment.js and undescore.js errors for now.  Is there a stable dev build I can work on?  If so just let me know the commit hash and I'll have a play. 

I would like to contribute a switch for high-contrast/low-contrast mode, and possibly some alternative script renders.  Also still having issue with double file headers.

**Comment by terryweiss** [comment]
I am also having trouble building. The last set of PRs merged, but they broke the build. I am still working on it, but am out of the country till next week. Be patient while I unwind the PRs and figure this out.

**Comment by terryweiss** [comment]
I didn't answer your question. Tag 0.4.15 is stable

**Comment by TimOgilvy** [comment]
Thanks Terry! 

I'll have a play with 0.4.15.   I've already come up with some tweaks to my CSS that make me happy. If I come up with anything generalisably useful I'll work towards a PR.

**Comment by TimOgilvy** [comment]
I'm pretty close to having a working alteration to 0.5.2  which allows switching between code highlighters.  So far I've got highlight.js and SyntaxHighlighter running in addition to sunlight.

**Comment by davidsan** [comment]
Hi, 
I'm also having issue with missing moment.js, and when I try to add it manually in the template folder jsdoc (3.3.0) complains about underscore.

It might be related to the path building, see #43.

**Comment by lukeapage** [comment]
@terryweiss please can you move the repo to the docstrap organisation - i invited you as an owner so we can get docstrap moving again. if you look at my user you'll see i have plenty of experience / kudos with github so you can trust me to be responsive. if you can add me to npm too (agatronic)  that would be useful. I'll wait a bit for your reply and then try contacting npm to transfer ownership of the package and finally as a last resort fork this repo to the organisation. @terryweiss @fisch0920

**Comment by terryweiss** [comment]
Yes, for sure. Thanks for taking this on. Give me a day or two to get this done. 

Thanks again, this project needs love.

**Comment by lukeapage** [comment]
thanks! just shout if you need any help with what to do.

**Comment by terryweiss** [comment]
OK, that all took less time than I expected. The project has been moved in github and I added agatronic as an owner in npm. I have not updated package.json to update urls or made any other changes. Can you confirm access and see if there is anything else you need from me? 

I'm really excited about this!

**Comment by lukeapage** [comment]
thanks, I'll take a look soon, have a clean up and see if anyone else wants
to be added to help.

**Comment by lukeapage** [comment]
All looks good.

**Comment by Telokis** [comment]
What about welcoming new maintainers?
The repo has 66PRs. Even if a lot of them are greenkeeper, this seems to be a lot.
I'd be glad to help if you need another hand.

/cc @lukeapage @terryweiss @tswaters
