### ISSUE TITLE
Version 0.4.15 of ink-docstrap causes grunt-jsdoc to fail

### ISSUE THREAD

**Issue by psbanka** [docstrap/docstrap#79]
(also filed this issue with [grunt-jsdoc](https://github.com/krampstudio/grunt-jsdoc/issues/116))

When running grunt jsdoc with the latest ink-docstrap `0.4.15`, jsdoc is failing with the following error:

```
10:29 $ grunt --verbose jsdoc
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-jsdoc" local Npm module tasks.
Reading /Users/pbanka/dev/cy-bootstrap/node_modules/grunt-jsdoc/package.json...OK
Parsing /Users/pbanka/dev/cy-bootstrap/node_modules/grunt-jsdoc/package.json...OK
Loading "jsdoc-plugin.js" tasks...OK
+ jsdoc
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ build, build-demo, build-dev, default, lint, post-coverage, test, test-coverage, test-debug, watch-build, watch-demo, watch-dev, watch-test

Running tasks: jsdoc

Running "jsdoc" task

Running "jsdoc:dist" (jsdoc) task
Verifying property jsdoc.dist exists in config...OK
Files: src
Options: private, destination="docs", recurse, template="node_modules/grunt-jsdoc/node_modules/ink-docstrap/template", configure="/Users/pbanka/dev/cy-bootstrap/node_modules/cy-toolkit/files/jsdoc.conf.json"
>> An error occurs in jsdoc process:
>> js: "/Users/pbanka/dev/cy-bootstrap/node_modules/grunt-jsdoc/node_modules/jsdoc/jsdoc.js", line 316: exception from uncaught JavaScript throw: Error: Unable to load template: Module "node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/publish" not found.
Warning: jsdoc failure Use --force to continue.
```

If the dependency to ink-docstrap is set to `0.4.12` instead of `~0.4.12`, jsdoc runs without problems.

**Comment by tswaters** [comment]
The version of jsdoc that ships with grunt-jsdoc is ~3.2.2 -- and without the latest jsdoc (3.3.0-beta1), things appear to be failing miserably.

Normally you'd be able to `npm install jsdoc` and grunt-jsdoc would pick up the version in your node_modules folder and use that, but in my limited testing, I'm not getting that now;  for some reason grunt-jsdoc is always picking up the version inside it's own node_modules directory.

Anyway, to fix this -- after running `npm install jsdoc`, you can add the following option to your `Gruntfile.js` in the jsdoc section to specify the path to the jsdoc bin file that grunt-jsdoc uses:

        "jsdoc": "node_modules/.bin/jsdoc",

@terryweiss it might be a good idea to roll back the recently merged changes, publish as 0.4.16 and republish #76 and #77 as 0.5.1.... I should have tested this on a vanilla install of grunt-jsdoc, my bad.

**Comment by terryweiss** [comment]
Thanks for the report and the quick analysis.

I backed off 0.4.15 and replaced it with 0.5.2. If someone could check grunt-jsdoc and make sure it pulls 0.4.12, I will close this issue.

**Comment by psbanka** [comment]
@tswaters thanks for the work-around. I have a report from another member of our team that they are having trouble with the current beta of `jsdoc`, so we're hoping the `grunt-jsdoc` folks can resolve the issue with the old version for the time being.

**Comment by krampstudio** [comment]
Last stable version of grunt-jsdoc use now only 0.4.12.

**Comment by lukeapage** [comment]
This seems solved, please let us know if it isn't
