### ISSUE TITLE
Links to static members do not work when smoothScrolling is on

### ISSUE THREAD

**Issue by Pilatch** [docstrap/docstrap#83]
It's a one-line fix to toc.js. In the scrollTo function, make this happen: 

var $el = $(elScrollTo.replace('#.', '#\\.'));

I'll see if I can make a pull request shortly...

**Comment by oct8cat** [comment]
+1
I can haz this in master? Got tired of opening toc static methods links in new tabs T_T

**Comment by Pilatch** [comment]
I made pull requests for this repo, and the underlying culprit, Table of Contents. Pretty simple fix. Hopefully it's just a matter of time.

**Comment by lukeapage** [comment]
I think this was merged, please come back if this was not fixed
