### ISSUE TITLE
v0.5.2: Layout glitches with spacelab theme

### ISSUE THREAD

**Issue by mwittig** [docstrap/docstrap#85]
I am trialing grunt-jsdoc@beta with docstrap 0.5.2 which works fine at a first glance, however, I noticed a few layout glitches when using the spacelab theme (may also apply for other themes):
- Page Heading (e.g. Class Name) is printed twice
- Highlighted Index Item for the current page is not readable as font color & background color appear to be the same
- All page text appears to be indented to the left by about 200px 

These glitches did not exist with v4.1.2 which I have also tested with grunt-jsdoc@beta (using the beta1 of JsDoc 3.3).

**Comment by mwittig** [comment]
What the status of pull request #84? It seems like the duplicate page heading and the highlighted index item issue had been fixed.

**Comment by mwittig** [comment]
https://github.com/terryweiss/docstrap/issues/89

**Comment by mwittig** [comment]
See also #89

**Comment by esatterwhite** [comment]
Don't think that it is specific to spacelab specifically, but the tutorials section is missing in 0.5.2. If I use the default theme it shows up.

**Comment by lukeapage** [comment]
http://docstrap.github.io/docstrap/themes/spacelab/

as of 0.5.3 the remaining issue is this:

> Highlighted Index Item for the current page is not readable as font color & background color appear to be the same

the next step is to see if it is because of docstrap or bootswatch

Are you interested in helping fix it?
