### ISSUE TITLE
org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined

### ISSUE THREAD

**Issue by chriscmr** [docstrap/docstrap#86]
I'm getting the following error message when I try to generate the JSDOC files using docstrap template.
What I am missing? I tried generating on different versions of JSDoc, from the stable 3.2 to 3.3-alpha9.
The default template works without issue.
Thanks

org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3785)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3763)
        at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3791)

**Comment by Lochemage** [comment]
Although the css file can be found there, the readme makes no mention of that as a valid template theme.  My guess is that it is just not supposed to work or it is used for some other reason other than as a theme.

**Comment by DaniGuardiola** [comment]
I'm having this issue too

### Output
>> An error occurs in jsdoc process:
>> org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined
>> 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3785)
>> 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3763)
>> 	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3791)
>> 	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3810)
>> 	at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:3823)
>> 	at org.mozilla.javascript.ScriptRuntime.getObjectPropNoWarn(ScriptRuntime.java:1541)
>> 	at org.mozilla.javascript.gen.file__home_dani_proyectos_paperkit_node_modules_ink_docstrap_template_publish_js_49._c_buildNav_21(Unknown Source)
>> 	at org.mozilla.javascript.gen.file__home_dani_proyectos_paperkit_node_modules_ink_docstrap_template_publish_js_49.call(Unknown Source)
>> 	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
>> 	at org.mozilla.javascript.gen.file__home_dani_proyectos_paperkit_node_modules_ink_docstrap_template_publish_js_49._c_anonymous_32(Unknown Source)
>> 	at org.mozilla.javascript.gen.file__home_dani_proyectos_paperkit_node_modules_ink_docstrap_template_publish_js_49.call(Unknown Source)
>> 	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
>> 	at org.mozilla.javascript.gen._home_dani_proyectos_paperkit_node_modules_grunt_jsdoc_node_modules_jsdoc_jsdoc_js_1._c_main_3(Unknown Source)
>> 	at org.mozilla.javascript.gen._home_dani_proyectos_paperkit_node_modules_grunt_jsdoc_node_modules_jsdoc_jsdoc_js_1.call(Unknown Source)
>> 	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
>> 	at org.mozilla.javascript.gen._home_dani_proyectos_paperkit_node_modules_grunt_jsdoc_node_modules_jsdoc_jsdoc_js_1._c_script_0(Unknown Source)
>> 	at org.mozilla.javascript.gen._home_dani_proyectos_paperkit_node_modules_grunt_jsdoc_node_modules_jsdoc_jsdoc_js_1.call(Unknown Source)
>> 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
>> 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
>> 	at org.mozilla.javascript.gen._home_dani_proyectos_paperkit_node_modules_grunt_jsdoc_node_modules_jsdoc_jsdoc_js_1.call(Unknown Source)
>> 	at org.mozilla.javascript.gen._home_dani_proyectos_paperkit_node_modules_grunt_jsdoc_node_modules_jsdoc_jsdoc_js_1.exec(Unknown Source)
>> 	at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)
>> 	at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:552)
>> 	at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
>> 	at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:499)
>> 	at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:215)
>> 	at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:134)
>> 	at org.mozilla.javascript.Context.call(Context.java:521)
>> 	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
>> 	at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
>> 	at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)

**Comment by DaniGuardiola** [comment]
Nevermind, I fixed it. The problem was that I was pointing to the wrong path, and I also was missing the config file.
FYI I was using grunt-jsdoc, also I just realized it comes included in that grunt plugin.

**Comment by SachaG** [comment]
Running into the same issue. It does seem like I might be specifying the wrong template path, but if that's the case I'm not sure how to find out the right one…

**Comment by DaniGuardiola** [comment]
@SachaG I can try to help you out if you give me some details. How are you running jsdoc? With grunt? Or CLI? What is the command you are using and where is your docstrap installed?

**Comment by SachaG** [comment]
I installed Docstrap with `npm install ink-docstrap` (also tried `npm install -g ink-docstrap`). 

This is what my configuration file looks like: https://gist.github.com/SachaG/43e1253fb8cc312f584b

And I've tried running it with both `jsdoc -c jsdoc.conf.json` and `jsdoc -c jsdoc.conf.json -t ../../node_modules/ink-docstrap/template`.

The first command works but gives me the usual JSDoc theme. The second command throws the `org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined` error.

**Comment by SachaG** [comment]
OK, so I got it to work using `grunt-jsdoc` for now.

**Comment by DaniGuardiola** [comment]
@SachaG ok, if you need any help just tell me so I can try to help

**Comment by lukeapage** [comment]
It seems like this is solved, please come back if this refers to an issue that needs fixing
