### ISSUE TITLE
Static method links throws error when clicked

### ISSUE THREAD

**Issue by cmoedk** [docstrap/docstrap#94]
The method is defined as such
   
     /**
    * @namespace enders
    */
    var enders = {};

    /**
     * Convert id to coordinate
     * @param id
     * @returns {enders.Coord}
     */
    enders.blockIdToCoord = function (id) {}

The link generated is : 

     ./docs/enders.html#.blockIdToCoord

And throws this error in the console, when I click the link

    Uncaught Error: Syntax error, unrecognized expression: #.blockIdToCoord

**Comment by froodian** [comment]
This error affects all module methods :(

**Comment by fabian1995** [comment]
I found a solution to this issue and commited it on my branch:
SHA:e787e506372e513a2d9430dad604245fc9a438e1

**Comment by lukeapage** [comment]
Fixed and released as 0.5.3
