### ISSUE TITLE
Give us control over sorting?

### ISSUE THREAD

**Issue by dwoldrich** [docstrap/docstrap#95]
It seems like your template inherited automagical (lexical?) sorting from jsdoc3's default template on this line:

https://github.com/terryweiss/docstrap/blob/master/template/publish.js#L453

Could you give us a boolean template config to enable disable that line?  I would like to inherit the "natural" order of symbols from my sources, even if that might wind up being a bit hinky at times whenever @lends does its thing.

Thanks!

**Comment by r-tanner-f** [comment]
Looks like it's checking for the `sort` property under `opts` and not `templates`. Was that intended and the documentation is just wrong? Or other way around?

**Comment by lukeapage** [comment]
as pointed out in #172.
I'm not sure.. is it ok under opts?

**Comment by dwoldrich** [comment]
Thanks for implementing (no) sort, can't wait to try it out!
