### ISSUE TITLE
Better getting started instructions?

### ISSUE THREAD

**Issue by SachaG** [docstrap/docstrap#98]
I feel like the README could stand to be improved with clearer, step by step instructions. 

I've successfully installed Docstrap with `npm install ink-docstrap`, but now what do I do next?

I configured my `conf.json` file and then tried running `jsdoc path/to/code -r -c conf.json`, but I still get the old JSDoc template. I then saw that you can configure a `-t` option, but I don't know which path to specify…

I'm happy to submit a PR to clarify the docs once I get this right :)

**Comment by creynders** [comment]
:+1: 
I have no idea how to get this up and running. Added a `theme` entry to `conf.json`but then what? Running `jsdoc index.js` still shows the default style. 

Then saw #100 and followed the advice, but there's no apparent change.

**Comment by fisch0920** [comment]
+1

**Comment by Riobe** [comment]
For anyone else that runs into this issue, here's how I'm doing it.

```bash
jsdoc -c path/to/conf.json -t ./node_modules/ink-docstrap/template -R README.md -r .
```

The `-c` sets the config, and the docstrap README does talk about the options you can put in templates that docstrap is supposed to look for.

The `-t` sets the template. This is the option you need to set to get the docstrap template to be used.

The `-R` sets a markdown file to be the front page of the documentation.

The `-r` tells jsdoc to run recursively.

The `.` says from current directory.

Modify as desired.
